name: Build Android APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        cache: true

    - name: Install dependencies
      working-directory: ./app
      run: flutter pub get

    - name: Build APK
      working-directory: ./app
      run: flutter build apk --debug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-debug-apk
        path: app/build/app/outputs/flutter-apk/app-debug.apk

    - name: Create or Update Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "app/build/app/outputs/flutter-apk/app-debug.apk"
        tag: "latest"
        name: "最新测试版本"
        body: "自动打包的最新 APK 安装包。"
        allowUpdates: true
        makeLatest: true
        token: ${{ secrets.GITHUB_TOKEN }}
